@url = https://be-k3g5.onrender.com/api
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU0OTMxNTYxLCJpYXQiOjE3NTQ5MzE1MDEsImp0aSI6ImM1NTM1NWU3YzMzYjRjYjFhOGNjOTJkMjgzZDFkN2U5IiwidXNlcl9pZCI6IjEifQ.jjksJSKlB84MvI55lyF6LkIYZwqvMs9aiLnfr3YCYu0
  "comment": "Great movie!"
}
###

DELETE {{url}}/movies/27/
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###
POST {{url}}/genres/
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "name": "phim hot1ư2"
}

###
PUT {{url}}/movies/28/
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "title": "edit",
    "description": "Phim khoa học viễn tưởng",
    "video_url": "https://example.com/inception.mp4",
    "poster_url": "https://example.com/inception.jpg",
    "release_year": 2010
}
###
GET {{url}}/genres/
# Content-Type: application/json
# Authorization: Bearer {{accessToken}}
###
PATCH  {{url}}/genres/2/
Content-Type: application/json
Authorization: Bearer {{accessToken}}
{
    "name": "Phim Hành Động"
}
###
GET {{url}}/genres/

###
DELETE  {{url}}/genres/4/
Content-Type: application/json
Authorization: Bearer {{accessToken}}



###
POST {{url}}/token/
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

###
POST {{url}}/token/refresh/
Content-Type: application/json

{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1Mzk3NjMzMSwiaWF0IjoxNzUzODg5OTMxLCJqdGkiOiI1Y2Q4MzkyNTRhOGM0M2YzYWZmOWNiYWNiOTQzMTBlNSIsInVzZXJfaWQiOiIxIn0.XbLCjIND_cYYb9YDFFPdc74DNFfDi5RN4tycMnwSMhw"
}