@url = https://be-k3g5.onrender.com/api
@accessToken =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU0NjU0OTAyLCJpYXQiOjE3NTQ2NTQ4NDIsImp0aSI6Ijg3N2I1OTI2NTY2NjQ0MGQ5NGZiMWU4MTUxYjdhMjQ0IiwidXNlcl9pZCI6IjEifQ.d6N8VSiRfkXVp40lc62zYfs1OAxq9TISE2laMeEpoeY
GET {{url}}/movies/11/

###
GET {{url}}/movies/
###

DELETE {{url}}/movies/27/
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###
POST {{url}}/movies/
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "title": "test2",
    "description": "Phim khoa học viễn tưởng",
    "video_url": "https://example.com/inception.mp4",
    "poster_url": "https://example.com/inception.jpg",
    "release_year": 2010
}

###
PUT {{url}}/movies/28/
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "title": "edit",
    "description": "Phim khoa học viễn tưởng",
    "video_url": "https://example.com/inception.mp4",
    "poster_url": "https://example.com/inception.jpg",
    "release_year": 2010
}
###
POST {{url}}/token/
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

###
POST {{url}}/token/refresh/
Content-Type: application/json

{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1Mzk3NjMzMSwiaWF0IjoxNzUzODg5OTMxLCJqdGkiOiI1Y2Q4MzkyNTRhOGM0M2YzYWZmOWNiYWNiOTQzMTBlNSIsInVzZXJfaWQiOiIxIn0.XbLCjIND_cYYb9YDFFPdc74DNFfDi5RN4tycMnwSMhw"
}